### ISSUE TITLE
RuntimeWarning in Gamma-Poisson Modeling

### ISSUE THREAD

**Issue by jaredgalloway** [lasersonlab/phip-stat#18]
Running the Gamma-Poisson on our data as well as the example data in this repository gives the warning:
```
lib/python3.6/site-packages/scipy/optimize/optimize.py:697: RuntimeWarning: invalid value encountered in double_scalars
  df = (f(*((xk + d,) + args)) - f0) / d[k]
```
This seems to be a precision error of some sort but I don't have a good feeling about what actual issues may arise from it in the results, if any. Could this be the result of converting to RCM (Read Counts Per Million) by hand instead of doing the size-factors normalization method?

https://stackoverflow.com/questions/7559595/python-runtimewarning-overflow-encountered-in-long-scalars

**Comment by laserson** [comment]
Sorry, totally missed this issue. I've always had that issue as well and never got to tracking it down. But AFAICT it didn't have any noticeable effects on the results.
