### ISSUE TITLE
How to input the "mock ips" matrix(PBS comtrol) during using the gamma-poisson-model? 

### ISSUE THREAD

**Issue by MSTU1995** [lasersonlab/phip-stat#19]
How to input the "mock IPs" matrix(PBS comtrol) during using the gamma-poisson-model? 
Is there any parameter to specify "mock ips"?
Does the gamma-poisson-model analysis method need to input "mock IPs" matrix ?

**Comment by laserson** [comment]
The Gamma Poisson model makes no distinction between mock IPs and not. It clips off the top percentile of data (which typically does not come from the mock IPs) and uses whatever is left to estimate the background distribution. So the more mock IP columns you add, the more accurate it will be able to estimate the background.

**Comment by MSTU1995** [comment]
Many thanks for your precious suggestion. 
As you said, how to set -t parameters is more reasonable，
and it has been bothered me that which analysis method is better , gamma-poisson-model or z-score method（https://github.com/LarmanLab/PhIP-Seq-Analyzer）.
