### ISSUE TITLE
about the compute-pvals commands

### ISSUE THREAD

**Issue by MrQ-095** [lasersonlab/phip-stat#20]
I use the `samtools idxstats` and the `cut -f` to get the input count tsv file, but when I run the compute-pvals command, it traceback this: 
    TypeError: expected non-empty vector for x 
I can run the example data , but I can not run mine. Is there something wrong with my data? or is it not appropriate to use the `samtools idxstats` to get the count file?

**Comment by laserson** [comment]
If `samtools idxstats` spits out a slightly differently shaped file than what `compute-pvals` expects, then it's not surprising that it breaks.

This project is not being very actively maintained. I would recommend checking out a more active project for this:
https://github.com/matsengrp/phippery

**Comment by MrQ-095** [comment]
Thanks! the "phippery" is very helpful. But I still have the trouble about getting the input count tsv file. I even tried to use the  "Example pipeline 3" and I still get the same traceback as before when calculating the P-vlaue. Could you please tell me how to get the input count tsv file?

**Comment by laserson** [comment]
Can you show a snippet of your file?

**Comment by MrQ-095** [comment]
https://drive.google.com/drive/folders/10dIZlPHrqApEN9pvtDVXLanwHZLqsPRx?usp=sharing
and my e-mail is wassily@yeah.net, if more detail needed, pls email me. 
My thanks and appreciation.

**Comment by laserson** [comment]
Could you just copy/paste a snippet into this issue?

**Comment by laserson** [comment]
If I had to guess, possible that your idxstats is maybe leaving out zeros?

**Comment by MrQ-095** [comment]
[sample1.txt](https://github.com/lasersonlab/phip-stat/files/6595198/sample1.txt)
This is partial of my count file.
Is too little zero in the count file bad?(there are some zeros in my whole count file but little)

**Comment by laserson** [comment]
Can you copy/paste the whole traceback?

**Comment by laserson** [comment]
Also, `compute-pvals` is deprecated (as the docs show). You should prefer the `gamma-poisson-model` anyway. But really you should probably use phippery.

**Comment by MrQ-095** [comment]
[traceback.txt](https://github.com/lasersonlab/phip-stat/files/6595421/traceback.txt)
This is the whole traceback.(I used `phip-stat` ver 0.3.0)
I reinstalled the latest verson of` phip-stat` and now the` phip gamma-poisson-model` are available. Working on it.

**Comment by laserson** [comment]
Let me know how it goes. And please copy paste text directly into the issue. I don't want to download files

**Comment by MrQ-095** [comment]
I use the  `phip gamma-poisson-model` to run my data following pepline1 and there is partial of my output. The N1-N3 are the negative sample. Is it normal that I get too much zero?
```
id	N3	N2	S2	N1	S3	S1
001	0.00	0.00	524.48	0.00	265.82	1502.90
002	15.85	46.09	0.00	2.74	0.00	0.00
003	40.30	108.45	0.00	12.31	-0.00	0.00
004	16.10	99.44	0.00	24.78	0.00	0.00
```

**Comment by MrQ-095** [comment]
And when I use phip-stat(ver 0.3.0) to run my data, I got the traceback :

**Comment by MrQ-095** [comment]
And when I run my data with phip-stat ver 0.3.0, I got the traceback :
```
Traceback (most recent call last):
  File "/home/zq/miniconda3/envs/phipseq/bin/phip", line 8, in <module>
    sys.exit(cli())
  File "/home/zq/miniconda3/envs/phipseq/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/zq/miniconda3/envs/phipseq/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/zq/miniconda3/envs/phipseq/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zq/miniconda3/envs/phipseq/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zq/miniconda3/envs/phipseq/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/zq/miniconda3/envs/phipseq/lib/python3.7/site-packages/phip/cli.py", line 276, in compute_pvals
    idxs)
  File "/home/zq/miniconda3/envs/phipseq/lib/python3.7/site-packages/phip/gp.py", line 105, in lambda_theta_regression
    coeffs = np.polyfit(idxs[i], thetas[i], 1)
  File "<__array_function__ internals>", line 6, in polyfit
  File "/home/zq/miniconda3/envs/phipseq/lib/python3.7/site-packages/numpy/lib/polynomial.py", line 599, in polyfit
    raise TypeError("expected non-empty vector for x")
TypeError: expected non-empty vector for x
```

**Comment by laserson** [comment]
The data is usually sparse since most samples will only bind to a small number of peptides. I also wouldn't use the `compute-pvals` command. Unfortunately I don't have much time to dig into the issue. If the Gamma-Poisson model works for you, go for it. If you want more support and newer models, I'd recommend you go with phippery.
