### ISSUE TITLE
phip merge-columns -m, no such option:-m

### ISSUE THREAD

**Issue by yimei-li** [lasersonlab/phip-stat#21]
When I am using the following code from the merge step of Example pipeline 3:

`phip merge-columns -m outer -i sample_counts -o counts.tsv`

I get this issue:

Usage: phip merge-columns [OPTIONS]
Try 'phip merge-columns -h' for help.
Error: No such option: -m

The option `phip merge-columns -m`  seems not exist. Any suggestions?

**Comment by laserson** [comment]
Hi Yimei, what is the output of `phip merge-columns -h` and what version are you using?

More importantly, I am no longer maintaining this repo. I'd suggest you check out phippery:
https://github.com/matsengrp/phippery
which is being actively maintained.

**Comment by yimei-li** [comment]
(python_phip_stat) mae@pop-os:~/0BrookLab/phip/phip_stat/try4$ phip merge-columns -h
Usage: phip merge-columns [OPTIONS]

  merge tab-delim files

Options:
  -i, --input TEXT        input path (directory of tab-delim files)
                          [required]
  -o, --output TEXT       output path  [required]
  -p, --position INTEGER  the field position to merge (0-indexed)
  -h, --help              Show this message and exit.

**Comment by yimei-li** [comment]
Sorry I think I don't see "-m" when use commend `phip merge-columns -h`

**Comment by yimei-li** [comment]
Could you please tell me which part/commend in **phippery** can be a good replacement for `phip merge-columns -m outer -i sample_counts -o counts.tsv`?

**Comment by laserson** [comment]
I'm not sure, but also check out phip-flow by the same group.

I suspect you may be using an older version of phip-stat. If you want to try to make it work, try installing with 

```
pip install git+https://github.com/lasersonlab/phip-stat.git
```

**Comment by yimei-li** [comment]
Awesome it worked!!!! Thank you so much!!!!!!!
