### ISSUE TITLE
[Troubleshooting] First Impression of PhiP-Seq 

### ISSUE THREAD

**Issue by Chuang1118** [lasersonlab/phip-stat#22]
Hello Author,

Thanks PhIP-Seq method to determine the binding of antibodies to epitopes.
My lab want to implement PhiP-Seq method.

I'm a bioinformatics guy, I have a few basic questions. 

I have finished syntheic peptidome library design (pepsyn: procedure 1-6) and Processing the Raw data (phip-stat: procedure 56-59) according to HHS Public Access Author manuscript. So I am in phase of tools testing.

Using miniconda, in environment pepsyn that has pepsyn and phip-stat, more details:
```
conda create -n pepsyn python=3.8
conda activate pepsyn
git clone https://github.com/lasersonlab/pepsyn.git
cd pepsyn
python setup.py install
conda install -c bioconda cd-hit
pip install git+https://github.com/lasersonlab/phip-stat.git
```
**Q1/ Procedure N° 1** 
input_orfs.fasta is same than https://github.com/lasersonlab/pepsyn/blob/master/pepsyn/tests/proteins.fasta ?
In the downstream, I have used proteins.fasta.

**Q2/ Procedure N° 5**
if output is empty, is good ? [code](https://github.com/lasersonlab/pepsyn/blob/a5969213e0a0ed5d514d7c5a730b93fcb78a5d2a/pepsyn/cli.py#L495)

**Q3/ Procedure N° 56 & Procedure N° 6** 
I download fastq with google [link](https://console.cloud.google.com/storage/browser/ll-nat-prot-ex-data/reads?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)
when I use bowtie --version , I got 
```
/usr/bin/bowtie:24: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
bowtie version 1.1.2
64-bit
Built on lgw01-11
Thu Nov 26 11:11:48 UTC 2015
```
I think here have a mistake. 
```
bowtie -n 3 -l 100 --best --nomaqround --norc -k 1 -p 4 --quiet \
bowtie_index/mylibrary workdir/reads/sample1.fastq.gz \
workdir/alns/sample1.aln
```
proof : I got  
```
Error: reads file does not look like a FASTQ file
terminate called after throwing an instance of 'int'
```
According  bowtie --help
```
/usr/bin/bowtie:24: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Usage: 
bowtie [options]* <ebwt> {-1 <m1> -2 <m2> | --12 <r> | <s>} [<hit>]
Input:
  -q                 query input files are FASTQ .fq/.fastq (default)
```
So bowtie can't support a compressed format, Can you provide your bowtie version. why not bowtie2 ?
With .fastq is works.
However, with the bowtie index generated by Procedure N° 6, I got sample1.aln **empty**.
```
total 8216
-rwxrwxrwx 1 dongc 5010 4195749 Jan 21 10:37 mylibrary.1.ebwt*
-rwxrwxrwx 1 dongc 5010     280 Jan 21 10:38 mylibrary.2.ebwt*
-rwxrwxrwx 1 dongc 5010     125 Jan 21 10:37 mylibrary.3.ebwt*
-rwxrwxrwx 1 dongc 5010     546 Jan 21 10:37 mylibrary.4.ebwt*
-rwxrwxrwx 1 dongc 5010 4195749 Jan 21 10:38 mylibrary.rev.1.ebwt*
-rwxrwxrwx 1 dongc 5010     280 Jan 21 10:38 mylibrary.rev.2.ebwt*
```
bowtie index download by google [link](https://console.cloud.google.com/storage/browser/ll-nat-prot-ex-data/bowtie_index?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)

```
total 9364
-rw-r--r-- 1 dongc 5010 4558470 Jan 21 12:25 mylibrary.1.ebwt
-rw-r--r-- 1 dongc 5010  105008 Jan 21 12:25 mylibrary.2.ebwt
-rw-r--r-- 1 dongc 5010   45008 Jan 21 12:26 mylibrary.3.ebwt
-rw-r--r-- 1 dongc 5010  210000 Jan 21 12:26 mylibrary.4.ebwt
-rw-r--r-- 1 dongc 5010 4558470 Jan 21 12:26 mylibrary.rev.1.ebwt
-rw-r--r-- 1 dongc 5010  105008 Jan 21 12:26 mylibrary.rev.2.ebwt
```
bowtie index google link is product by  Procedure N° 1 as Input ?
if yes, here is a big trouble for me.
if no, how about Input?

**Q4/ Procedure N° 57 & Procedure N° 58**  
```
phip --help
Usage: phip [OPTIONS] COMMAND [ARGS]...
Commands:
  compute-counts               (**Deprecated**) Compute counts from aligned bam file.
  compute-pvals                (**Deprecated**) Compute p-values from counts.
```
I don't get errors, but here marker as Deprecated. I have got the results.
```
DeprecationWarning: The command 'compute-counts' is deprecated.
/path/workdir/alns/sample1.aln

DeprecationWarning: The command 'compute-pvals' is deprecated.
Loading data: 5000it [00:00, 779320.70it/s]
Unique input values: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 90/90 [00:00<00:00, 8402.24it/s]
GenPois sample estimates: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 89.29it/s]
Parameter regression: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1520.78it/s]
Precomputing p-vals: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1480/1480 [00:01<00:00, 785.09pval/s]
Writing scores: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [00:00<00:00, 543627.55it/s]
```
**Q5/ In your google link** [ref_dna_tiles.fasta](https://console.cloud.google.com/storage/browser/ll-nat-prot-ex-data/ref?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false).
What is this file ? Product by which number Procedure ?

**Q6/ General question about exchange between Bioinformatician (me) and biologist.**
I just need give **oligos.fasta** to biologist after step Synthetic Peptidome Library Design [1-6]?
Then [7-55] the biologist give me **sample1.fastq.gz** and **counts.tsv**?
Finally[56-60], data analysis.

Best regards,
Chuang

**Comment by laserson** [comment]
Hi @Chuang1118, thanks for the detailed messages. Unfortunately phip-stat is no longer being supported, and I don't have the bandwidth to help you work through these issues. Check out Erick Matsen's phippery, or connect with Ben Larman's group for advice.
