### ISSUE TITLE
`phip normalize-counts`

### ISSUE THREAD

**Issue by FarzanehRah** [lasersonlab/phip-stat#23]
Hi,
I would like to use the `phip normalize-counts` command to normalize a matrix of VirScan data. I have two questions regarding this command:

1. What normalization method does the `phip normalize-counts` command use?

1. What are the specific requirements for the input file? Should the input file contain only samples or ‘beads-only’ or ‘mock should be part of the normalization?

I would like also to know if there are any other resources available, such as documentation or tutorials, that provide more detailed information on using phip.
I greatly appreciate any help you can provide in answering these questions. Thank you.

**Comment by laserson** [comment]
Hi @FarzanehRah, this package is no longer being maintained. I suggest you check out either:
- phippery (python): https://github.com/matsengrp/phippery
- BEER (R/Bioconductor): https://github.com/athchen/beer/
for more maintained packages.
